[package]
name = "nostr-block-alert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = "0.18"
tokio = { version = "1", features = ["full"] }