CREATE TABLE alert_types(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    val TEXT NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

/*
 * 1) UTXO_MOVEMENT - utxo movement (need actual utxo to watch)
 * 2) TRANS_CONFIRM_HEIGHT - transaction confirmation height (need height)
 * 3) MEMPOOL_FEE_LEVEL - mempool fee hitting a given threshold (need fee value in vbytes)
 * 4) BLOCK_HEIGHT - a given block height has been reached (need height)
*/
INSERT INTO alert_types(val)
VALUES
    ('UTXO_MOVEMENT'),
    ('TRANS_CONFIRM_HEIGHT'),
    ('MEMPOOL_FEE_LEVEL'),
    ('BLOCK_HEIGHT');

-- Add migration script here
CREATE TABLE alerts(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 50000 INCREMENT BY 1),
    alert_type_id INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    requestor_pk TEXT NOT NULL, --nostr public key of the individual asking for the alert to be sent to them
    threshold_num BIGINT, -- block height and fee go here
    identifier TEXT, -- UTXO would go here
    sent_at TIMESTAMPTZ,
    sent_responsed JSONB, -- might end up dropping, not sure
    PRIMARY KEY(id),
    CONSTRAINT fk_request_type
      FOREIGN KEY(alert_type_id) 
	  REFERENCES alert_types(id)
);
