mempool:
  #url: "https://mempool.space"
  url: "http://localhost:8999"
database:
  host: "127.0.0.1"
  port: 15415
  username: "postgres"
  password: "password"
  database_name: "nostrmempoolalerts"
  require_ssl: false
nostr:
  private_key: ""
  nostr_relays:
   - ""
   - ""