mempool:
  url: "mutinynet.com"
  #url: "https://mempool.space/"
  #url: "https://mempool.space/signet"
database:
  require_ssl: false
nostr:
  private_key: "nsec1m4ca60u9sdeesn8uhghfgedz8plva68yavnr4g4s7x0tl372tavqsecwtq"
  #public_key: "npub13mc3253t0qgywsvkxw6fdlypts4ewt4f0cukam07xq50s4z4j59qd23t2y"
  nostr_relays:
   - "ws://0.0.0.0:8080"