mempool:
  url: "mutinynet.com"
  #url: "https://mempool.space/"
  #url: "https://mempool.space/signet"
database:
  require_ssl: false
nostr:
  private_key: "nsec1rlpycvsa8xuyuqumsdgcssengqc65j87fnmwpffkv7a2tgj3gc0sltukmh"
  nostr_relays:
   - "ws://0.0.0.0:8080"